notifications:
  slack: seedpay:DLzoxbzAuv42TZ4EnoK91xJk
cache:
  directories:
  - node_modules
  - vendor
fail_fast: true
env:
  global:
  - NODE_ENV=travis
stages:
- Compile and test js
- Test php
jobs:
  include:
  - stage: Compile and test js
    script: npm install && npm run buildprod && npm test
  - stage: Test php 
    script: composer install && composer test