language: php
php:
  - '7.3'
notifications:
  slack: seedpay:DLzoxbzAuv42TZ4EnoK91xJk
cache:
  directories:
  - node_modules
  - vendor
fail_fast: true
env:
  global:
  - NODE_ENV=travis
stages:
- Compile and test
- Test php
jobs:
  include:
  - stage: Compile and test
    script: npm install && npm run buildprod && npm test && composer install && composer test